#ifndef I2C_H
#define I2C_h

#define     pI2C      (((pLPC_I2C) 0xE001C000))

typedef struct _I2C{
  U32 CONTROL_SET_REGISTER;
  U32 STATUS_REGISTER;
  U32 DATA_REGISTER;
  U32 SLAVE_ADDRESS_REGISTER;
  U32 DUTY_CYCLE_HIGH_HALF_WORD_REGISTER;
  U32 DUTY_CYCLE_LOW_HALF_WORD_REGISTER;
  U32 CONTROL_CLEAR_REGISTER;
}LPC_I2C,*pLPC_I2C;





#endif
